# Generated by Django 4.0.3 on 2022-03-11 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_date_post_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='photo',
        ),
    ]
